CREATE TABLE EMPLOYEE (ID INTEGER AUTO_INCREMENT NOT NULL, LEVEL VARCHAR(255), NAME VARCHAR(255), SALARY INTEGER, PRIMARY KEY (ID))
CREATE TABLE STUDENT (ID INTEGER AUTO_INCREMENT NOT NULL, ENROLLMENTID VARCHAR(255), NAME VARCHAR(255), TUTORNAME VARCHAR(255), PRIMARY KEY (ID))
